Algoritmo ElapocalipsisZombie
	Definir matrix,muestra,vector Como Caracter
	
	Dimension matrix(35,35)
	Dimension vector(1225)
	muestra="ACCDBBADDDCCBACABDCBDCBADBDACBBBBDAABBCCBAACCABDBDCDDABDBDADAAACBBBBCDDDCBBBDDCDABBDDABDBDBBACADCDAAADACDDDACCDCACDDABACDCCCAABDDCCACDADDBCBAACCDBCBCDDDCAACCBAADCBBBCDCBBACBDCCDDADBABCAABBACABDCAACCBDADDCAAACCDBDBBCDDDDDACBCDDADDDDCBADADBDCADDABBCDAACBCCDDDADDADADAACCACDCDDABCCCADABBACDACCAADDBCBCCDADBCCADAAABDDDAABBABCADDCCAADDCDDCDCACBADADACADDAADCBDBCDBDDACDCBCDCCABBDCBACDDACCCDADBCADCACAAABBBCADDDDBCBACDBDAAADDDACCDACBBBADACCCDCACCBACDADBCBBDADACABAACBCCADDCCCCACCCCADBCCDAADCAABBABAADDBDADDABABCCABBCDDACCADAAADBBCCDBADCADCBBDADACCDDBCAAABBBDCAAAACBAADBABBABACDDBBCBDCDCADABABBDADCBADAACDBCBDABADBCBADCACADAABCDDCABACDDBDCBCBDCAAACBDABBCACBACCCBACACDCADBDCDCDDCAACDBDCBACDBBDAABDBBCBAAADBABDBAACAAACDCDAAABABDDDBCACADCBBAADCCDABCCCBBCACCBAABDAADDDCDACDDDBCDCCBABDABACCDCDCDABAABCABBADADCBDDACDDCDDCDACDADADCACBCDABABDDCCDBCCDABACDBDAABDBDDDBADDBACABDCDDBACDDBBDDBBACBCCAACABBDADDBCAACCBCCDADDBCAADDADCCCBAAABABBBBBCABAACADBCBBABACCABCDAABADCCCCDCCADDDCCABBDDDAAADDADACBBBCBDAADACABABBAACCCADADDABDBCADDDCCDBBCCBCDCDBDDDDCACDACDBBBDDBADDACADDADDABCACDCBBADDABBBDCBBDCDAABADDDDDBCACCCCAAACBCBCDBACCCDACCCDBCBDCBADBCDDACCDBDBDBCAAACDDCBAABDBCAADCADDBABABDCBCBCBBBCACBCADDCAAAAAACBBACBBCCACBDCDDDDADCAAACBABDDBDADBAADCBABDDBCDBABDBAADDDBACBBBCCCDBDDBDDAADBBADADDDCBCACBABCDBBABAADABCABCDBACBBBCDBADADDBDCBDABBDDDCDDCCACDCBDCADABAABCDCAACCDDBADBDBCDACAAACBCADCCCBAC"

	llenarvectorPalabra(matrix, muestra, vector,1225)
	llenarmatrizPalabra(matrix, muestra, vector,1225)
    verificarmatriz(matrix, 4,4)
	
FinAlgoritmo

SubProceso llenarvectorPalabra(matrix, muestra, vector,1225)
	Definir d Como Entero
	
	Para d=0 Hasta 1224 Con Paso 1 Hacer
		vector(d)=Subcadena(muestra,d,d)
//		Escribir Sin Saltar vector(d)
	Fin Para
	
FinSubProceso

SubProceso llenarmatrizPalabra(matrix, muestra, vector Por Referencia,1225)
	Definir i,j,d Como Entero
	d=0
	para i=0 Hasta 34 Hacer
		Para j=0 Hasta 34 Hacer
			matrix(i,j)=vector(d)
			Escribir matrix(i,j) Sin Saltar
			d=1+d
		FinPara
		Escribir " "
	FinPara
	
FinSubProceso

SubProceso verificarmatriz(matrix Por Referencia,35,35)
	Definir i,j Como Entero
	
	Para i=0 Hasta 34 Con Paso 1 Hacer
		Para j=0 Hasta 34 Con Paso 1 Hacer
			si matrix(0,0)=matrix(1,1) y matrix(2,2)=matrix(3,3) 
				Escribir "es verdadera"
			SiNo
				Escribir "no es correcto"
				
			FinSi
		Fin Para
    Fin Para
	
FinSubProceso
	